apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "personal-site.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "personal-site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "personal-site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "personal-site.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: website
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.secrets.enabled }}
          env:
            - name: PGH_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "personal-site.fullname" . }}-secrets
                  key: database-url
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
