{{- if .Values.secrets.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: personal-site-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    database-url: AgAivcGWevpmJcbA8ckkzk+ByEU3AtAgP+AQSk3OEjoUTlJJYNZab8QxVPfdGNb5hQOyF51jP/m6ip3zOKTg2WOTgDKewwU+w2N2KjAaT/6bN+6gGQVfKApOvuEVw5PhdOutllbyvggkJrSO0fqudAE/4KOyrPqIic6nB0VTqSWdUK1CDuPV9c6ESfDzFVpAlRQM70srlYMJqvn6gB4AScd7OyaHMas7PXuyLhcLMHO/nD7BLuaz0VkYmOq1vbnfRyorRNXHAhiG1oFYDkpDht3Sr0V144PgYXE+PyjDRh2wb1wzim3YdKFRbUcGU8+17A4O5Xz2tRa0bBMTWW38K1v3p/Et4lz2KF2PyWTC/ee1cgJdEdRJ22oVKFX7OYdH3oCywiXXCfvGsOyRsEQVs47g6+YNr3NpnN3nB/QehUeU6jT+R4dffe7tNJMjaE8dUZkDCl/pFIeV6noeXW8QDhL5kTXzwM1CB4n7mYIQrYib12RPjxObErFb0zTA42r/AioMt7rXFyJ6pvB+BntMxpJzSkwW+YkvrUj/Gsi5JRk6HpYAvtx8HTPlBr8EQmfI+Aa3yq2qessGkElVVJzGnv/5XRPWJKwgS3fUJnqFUi3z8y9Y3aYk6GX6Mb/ORbRwaWd+RtG1/mcw5uRCB/TKU5XzeNgUg7ukt7MpIHDHn0i1/wkKDEiCFSkPq41XVc/8hxhK3ltQjc2pNEzXAFXLF3VhZjD9IVIqhXqgcolKQa/93bMiQt5ZleSJpcaLIxHnoJpxQQmVMFnD/cjm3Q8FWU9J1GNBGcbG+c52e7DNAt7FP5uw5ds76aCjikF+T5d6fw==
    postgres-password: AgCUvg/iWEBoblFFKFyPDupAjBmz1GogG9My0FP5Zby5Fgu3msA6rZhzdQ8c6c0OpNs6E2n6VBiY+mDpwcFtd9nMh7vHiRpijpuA60hDNfBoTxXg9bH6PulAtql8SMPghgSfIxN5icB8+n74nIKt2a3QgPcZR7Tjx5/UZd1ST9dh1N9x/voKstGn+62FkUPTjr272CuGekwPmLnXmRqGfT+J3lc/LEHV0sCOX5KinCnTcbCJCiz+xWBhaAgVh8dOxWSRT4qOlvTMjQa7keRG/x3wG4iqZGQsHSA4VzaL5xyojeWX/VMfqugFWwB5lei+4+zKUpMMhdVwapt+/jip6/yAx8DLuog8jo9fcCaMQwxF2ZjK+jh38lntMrylot68KSozvaik/s4bXWEM6eG68jIUBPAnDjMz1u3vnOm1QTiH5JaSolw8/TVVgXyFeeR6f1u3XEdhdCtaXG4juIp5r9uTV+3MACm7oSWgTpRuIEyklq6nquOfa5xzqh2SwUI/GOxWf6ciJyNlwFgGDm/0l6c/lGZcmeDFXfuKYFzQ58aIuj9Y/4Ksdzbo1uvu22PF+TdTp8qJkdPmaedoVJos7WLEsv5IBFjoWCC6YVQ7tIVfBrDhbw+fAlulQa5qVhu78r9Nfmp9RGWK64oeOp0agWeygFkxqiA2LzqLRDMnI/tkAOsSuJ9yVuuXi0vsx4qa0rYhODQEquMHZs44a36hD0FiPKkITyVW47EkNALKWfpITw==
  template:
    metadata:
      name: personal-site-secrets
      namespace: {{ .Release.Namespace }}
{{- end }}
